"""add_bookmark_model

Revision ID: 53a3caabc40d
Revises: 6a57fafbd942
Create Date: 2025-08-26 21:36:42.843486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a3caabc40d'
down_revision: Union[str, None] = '6a57fafbd942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('article_title', sa.String(), nullable=False),
    sa.Column('article_url', sa.String(), nullable=False),
    sa.Column('article_source', sa.String(), nullable=True),
    sa.Column('article_summary', sa.Text(), nullable=True),
    sa.Column('article_sentiment', sa.String(), nullable=True),
    sa.Column('article_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_bookmarks_article_id'), 'bookmarks', ['article_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_article_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
